export interface CompanionResourceDescriptionInterface {
    name: string;
    img: string;
    behaviour: "dog" | "cat";
}

export const COMPANION_RESOURCES: CompanionResourceDescriptionInterface[] = [
    { name: "bear1", img: "resources/characters/pipoya/Bear 01-1.png", behaviour: "dog" },
    { name: "bear2", img: "resources/characters/pipoya/Bear 01-2.png", behaviour: "dog" },
    { name: "butterfly1", img: "resources/characters/pipoya/Butterfly 01-1.png", behaviour: "dog" },
    { name: "butterfly2", img: "resources/characters/pipoya/Butterfly 01-2.png", behaviour: "dog" },
    { name: "camel1", img: "resources/characters/pipoya/Camel 01-1.png", behaviour: "dog" },
    { name: "camel2", img: "resources/characters/pipoya/Camel 01-2.png", behaviour: "dog" },
    { name: "dog1", img: "resources/characters/pipoya/Dog 01-1.png", behaviour: "dog" },
    { name: "dog2", img: "resources/characters/pipoya/Dog 01-2.png", behaviour: "dog" },
    { name: "dog3", img: "resources/characters/pipoya/Dog 01-3.png", behaviour: "dog" },
    { name: "dog4", img: "resources/characters/pipoya/Dog 01-4.png", behaviour: "dog" },
    { name: "dog5", img: "resources/characters/pipoya/Dog 01-5.png", behaviour: "dog" },
    { name: "dog6", img: "resources/characters/pipoya/Dog 01-6.png", behaviour: "dog" },
    { name: "dog7", img: "resources/characters/pipoya/Dog 01-7.png", behaviour: "dog" },
    { name: "corgi1", img: "resources/characters/pipoya/Corgi 01-1.png", behaviour: "dog" },
    { name: "corgi2", img: "resources/characters/pipoya/Corgi 01-2.png", behaviour: "dog" },
    { name: "cat1", img: "resources/characters/pipoya/Cat 01-1.png", behaviour: "cat" },
    { name: "cat2", img: "resources/characters/pipoya/Cat 01-2.png", behaviour: "cat" },
    { name: "cat3", img: "resources/characters/pipoya/Cat 01-3.png", behaviour: "cat" },
    { name: "fox1", img: "resources/characters/pipoya/Fox 01-1.png", behaviour: "cat" },
    { name: "fox2", img: "resources/characters/pipoya/Fox 01-2.png", behaviour: "cat" },
    { name: "fox3", img: "resources/characters/pipoya/Fox 01-3.png", behaviour: "cat" },
    { name: "frog1", img: "resources/characters/pipoya/Frog 01-1.png", behaviour: "dog" },
    { name: "frog2", img: "resources/characters/pipoya/Frog 01-2.png", behaviour: "dog" },
    { name: "goose1", img: "resources/characters/pipoya/Goose 01-1.png", behaviour: "dog" },
    { name: "goose2", img: "resources/characters/pipoya/Goose 01-2.png", behaviour: "dog" },
    { name: "goose3", img: "resources/characters/pipoya/Goose 01-3.png", behaviour: "dog" },
    { name: "koala1", img: "resources/characters/pipoya/Koala 01-1.png", behaviour: "dog" },
    { name: "ostrich1", img: "resources/characters/pipoya/Ostrich 01-1.png", behaviour: "dog" },
    { name: "ostrich2", img: "resources/characters/pipoya/Ostrich 01-2.png", behaviour: "dog" },
    { name: "panda1", img: "resources/characters/pipoya/Panda 01-1.png", behaviour: "dog" },
    { name: "penguin1", img: "resources/characters/pipoya/Penguin 01-1.png", behaviour: "dog" },
    { name: "penguin2", img: "resources/characters/pipoya/Penguin 01-2.png", behaviour: "dog" },
    { name: "penguin3", img: "resources/characters/pipoya/Penguin 01-3.png", behaviour: "dog" },
    { name: "penguin4", img: "resources/characters/pipoya/Penguin 01-4.png", behaviour: "dog" },
    { name: "platypus1", img: "resources/characters/pipoya/Platypus 01-1.png", behaviour: "dog" },
    { name: "platypus2", img: "resources/characters/pipoya/Platypus 01-2.png", behaviour: "dog" },
    { name: "polarbear1", img: "resources/characters/pipoya/Polar Bear 01-1.png", behaviour: "dog" },
];
