export interface CompanionResourceDescriptionInterface {
    name: string;
    img: string;
    behaviour: "dog" | "cat";
}

export const COMPANION_RESOURCES: CompanionResourceDescriptionInterface[] = [
    { name: "dog1", img: "resources/characters/pipoya/Dog 01-1.png", behaviour: "dog" },
    { name: "dog2", img: "resources/characters/pipoya/Dog 01-2.png", behaviour: "dog" },
    { name: "dog3", img: "resources/characters/pipoya/Dog 01-3.png", behaviour: "dog" },
    { name: "cat1", img: "resources/characters/pipoya/Cat 01-1.png", behaviour: "cat" },
    { name: "cat2", img: "resources/characters/pipoya/Cat 01-2.png", behaviour: "cat" },
    { name: "cat3", img: "resources/characters/pipoya/Cat 01-3.png", behaviour: "cat" },
    { name: "bear1", img: "resources/companions/Bear 01-1.png", behaviour: "dog" },
    { name: "bear2", img: "resources/companions/Bear 01-2.png", behaviour: "dog" },
    { name: "beaver1", img: "resources/companions/Beaver 01-1.png", behaviour: "dog" },
    { name: "butterfly1", img: "resources/companions/Butterfly 01-1.png", behaviour: "dog" },
    { name: "butterfly2", img: "resources/companions/Butterfly 01-2.png", behaviour: "dog" },
    { name: "camel1", img: "resources/companions/Camel 01-1.png", behaviour: "dog" },
    { name: "camel2", img: "resources/companions/Camel 01-2.png", behaviour: "dog" },
    { name: "dog4", img: "resources/companions/Dog 01-4.png", behaviour: "dog" },
    { name: "dog5", img: "resources/companions/Dog 01-5.png", behaviour: "dog" },
    { name: "dog6", img: "resources/companions/Dog 01-6.png", behaviour: "dog" },
    { name: "dog7", img: "resources/companions/Dog 01-7.png", behaviour: "dog" },
    { name: "dragon1", img: "resources/companions/Dragon 01-1.png", behaviour: "dog" },
    { name: "dragon2", img: "resources/companions/Dragon 01-2.png", behaviour: "dog" },
    { name: "dragon3", img: "resources/companions/Dragon 01-3.png", behaviour: "dog" },
    { name: "dragon4", img: "resources/companions/Dragon 01-4.png", behaviour: "dog" },
    { name: "duck1", img: "resources/companions/Duck 01-1.png", behaviour: "dog" },
    { name: "corgi1", img: "resources/companions/Corgi 01-1.png", behaviour: "dog" },
    { name: "corgi2", img: "resources/companions/Corgi 01-2.png", behaviour: "dog" },
    { name: "fox1", img: "resources/companions/Fox 01-1.png", behaviour: "cat" },
    { name: "fox2", img: "resources/companions/Fox 01-2.png", behaviour: "cat" },
    { name: "fox3", img: "resources/companions/Fox 01-3.png", behaviour: "cat" },
    { name: "frog1", img: "resources/companions/Frog 01-1.png", behaviour: "dog" },
    { name: "frog2", img: "resources/companions/Frog 01-2.png", behaviour: "dog" },
    { name: "goose1", img: "resources/companions/Goose 01-1.png", behaviour: "dog" },
    { name: "goose2", img: "resources/companions/Goose 01-2.png", behaviour: "dog" },
    { name: "goose3", img: "resources/companions/Goose 01-3.png", behaviour: "dog" },
    { name: "koala1", img: "resources/companions/Koala 01-1.png", behaviour: "dog" },
    { name: "mario1", img: "resources/companions/Mario 01-1.png", behaviour: "dog" },
    { name: "ostrich1", img: "resources/companions/Ostrich 01-1.png", behaviour: "dog" },
    { name: "ostrich2", img: "resources/companions/Ostrich 01-2.png", behaviour: "dog" },
    { name: "owl1", img: "resources/companions/Owl 01-1.png", behaviour: "dog" },
    { name: "panda1", img: "resources/companions/Panda 01-1.png", behaviour: "dog" },
    { name: "pokemon1", img: "resources/companions/Pokemon 01-1.png", behaviour: "dog" },
    { name: "pokemon2", img: "resources/companions/Pokemon 01-2.png", behaviour: "dog" },
    { name: "penguin1", img: "resources/companions/Penguin 01-1.png", behaviour: "dog" },
    { name: "penguin2", img: "resources/companions/Penguin 01-2.png", behaviour: "dog" },
    { name: "penguin3", img: "resources/companions/Penguin 01-3.png", behaviour: "dog" },
    { name: "penguin4", img: "resources/companions/Penguin 01-4.png", behaviour: "dog" },
    { name: "platypus1", img: "resources/companions/Platypus 01-1.png", behaviour: "dog" },
    { name: "platypus2", img: "resources/companions/Platypus 01-2.png", behaviour: "dog" },
    { name: "polarbear1", img: "resources/companions/Polar Bear 01-1.png", behaviour: "dog" },
    { name: "shark1", img: "resources/companions/Shark 01-1.png", behaviour: "dog" },
    { name: "shark2", img: "resources/companions/Shark 01-2.png", behaviour: "dog" },
    { name: "sheep1", img: "resources/companions/Sheep 01-1.png", behaviour: "dog" },
];
